### ISSUE TITLE
Missing FLUSH PRIVILEGES

### ISSUE THREAD

**Issue by BrianAker** [Tknika/openhab2-mysql-installation-script#1]
Around line 90 you need to add:

> FLUSH PRIVILEGES;

That will cause the database to update its in memory cache of users.

I would also recommend setting the default storage engine to Innodb.

**Comment by bodiroga** [comment]
Hi @BrianAker!

Many thanks for opening a new issue and for your suggestions!

The script just implements the steps described in the following tutorial: https://github.com/openhab/openhab1-addons/wiki/Ubuntu-on-x64#mysql-for-persistence, but for sure we can improve it! I will add the "FLUSH PRIVILEGES;" statement after the "GRANT ALL PRIVILEGES" command.

I have been reading about the default storage engine and it seems that the latest versions of MySQL already defines Innodb as the default engine: https://dev.mysql.com/doc/refman/5.5/en/storage-engines.html. Do you think that we should fine tune any engine parameters?

Thanks again and best regards,

Aitor

**Comment by bodiroga** [comment]
Ummmm... I have found this article that talks about the FLUSH PRIVILEGES command:

http://dbahire.com/stop-using-flush-privileges/

I'm not an MySQL expert, but it seems that it is not necessary after a "GRANT ALL PRIVILEGES" command. What is your recommendation?

**Comment by BrianAker** [comment]
First, let me answer your question about "GRANT ALL PRIVILEGES".  You are only granting the permissions that the user who made the GRANT had, minus a certain set of permissions not defined by SQL99 ( this is some very esoteric logic that is not user obvious ( and the argument for this was decided/reargued/etc over a decade ago, the current argument for this behavior may now be different )).

As to your second question was about GRANT and what it should do vs what it does. 
There are "corner cases"/bugs/"option setting" which all influence whether or not this will work as advertised. When I was reading through the OpenHAB forums/blogs about different setup options/requests for help, most of the users issues were related to the priv tables not being flushed to disk ( assuming the individuals for help did what they said they did ).

I also ran forked loop for 'hell of it against my local MySQL instance and got back a few connection errors which looked to be likely the result of GRANT not being quite as atomic as the documents say it is.

Off the top of my head, the reason to not run FLUSH fall roughly into two categories, one being "performance" and the other being "pedantic". 

The user friendly solution is to call FLUSH; in my opinion, ease of install would rate higher then the two reasons I listed for "not call FLUSH".

I would offer a suggestion that you consider adding a comment/pointer to this discussion so that anyone who submits a bug in the future for "you don't need to call flush", can see the reasons for why you should consider calling FLUSH.

If you needed a final reason as to why you should call FLUSH,  by calling FLUSH the GRANT will be logged in REPLICATION so any recovery will contain the GRANT statement ( maybe someone is really trying to create an HA OpenHAB setup?).

If you have any other questions, feel free to ask. I hopefully did not make my answer to concise.

I think it is awesome that you published the steps found in the forums, so many open source projects fail at "ease of use" which begins with "can anyone install XYZ?".

**Comment by bodiroga** [comment]
Hi @BrianAker!

Many thanks for your detailed response, even if my knowledge about MySQL (and databases in general) is not very deep! I will re-read it a couple of times more :wink:  I will add the "FLUSH PRIVILEGES;" right now then. 

Many thanks for your help and if you have more suggestions don't hesitate to make them :+1:
